# Generated by Django 4.2.7 on 2023-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0002_calificaciones_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='name',
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
