# Generated by Django 4.2.7 on 2023-12-12 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0003_cursos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entregatareas',
            name='fechaEntrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tareas',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='titulo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
