# Generated by Django 4.2.7 on 2023-12-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0004_cursos_description_entregatareas_fechaentrega_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameModel(
            old_name='EntregaTareas',
            new_name='EntregaTarea',
        ),
        migrations.RenameModel(
            old_name='Calificaciones',
            new_name='Nota',
        ),
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tarea',
        ),
    ]
