# Generated by Django 4.2.7 on 2023-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0005_rename_cursos_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
    ]
