# Generated by Django 4.2.7 on 2023-12-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0009_entregatarea_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregatarea',
            name='file',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
