# Generated by Django 4.2.7 on 2023-12-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0010_alter_entregatarea_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregatarea',
            old_name='file',
            new_name='Comentarios',
        ),
    ]
