# Generated by Django 5.0 on 2023-12-13 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0011_rename_file_entregatarea_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregatarea',
            name='Comentarios',
            field=models.CharField(default='', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='estudiante',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentsTasks.estudiante'),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='fechaEntrega',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentsTasks.tarea'),
        ),
    ]
