# Generated by Django 5.0 on 2023-12-13 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0012_alter_entregatarea_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregatarea',
            name='Comentarios',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentsTasks.estudiante'),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='fechaEntrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentsTasks.tarea'),
        ),
    ]
