# Generated by Django 5.0 on 2023-12-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0013_alter_entregatarea_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='archivo',
            field=models.FileField(null=True, upload_to='entregas/'),
        ),
    ]
