# Generated by Django 5.0 on 2023-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0014_entregatarea_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(null=True, upload_to='entregas/'),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='archivo',
            field=models.FileField(null=True, upload_to='', verbose_name='Tarea'),
        ),
    ]
