# Generated by Django 5.0 on 2023-12-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0015_tarea_archivo_alter_entregatarea_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregatarea',
            name='archivo',
        ),
    ]
