# Generated by Django 5.0 on 2023-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0016_remove_entregatarea_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregatarea',
            name='fechaEntrega',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
