# Generated by Django 4.2.7 on 2023-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0019_estudiante_birthdate_estudiante_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregatarea',
            name='Comentarios',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
