# Generated by Django 5.0 on 2023-12-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsTasks', '0023_alter_estudiante_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
    ]
